# Generated by Django 5.0.6 on 2024-07-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tortas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupcake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('cubierta', models.CharField(max_length=200)),
                ('relleno', models.CharField(max_length=250)),
                ('docenas', models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='tortap',
            name='agregados',
            field=models.CharField(max_length=50),
        ),
    ]
