# Generated by Django 5.0.6 on 2024-07-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tortas', '0002_cupcake_alter_tortap_agregados'),
    ]

    operations = [
        migrations.AddField(
            model_name='torta',
            name='precio',
            field=models.DecimalField(decimal_places=3, default=500.5, max_digits=10),
        ),
    ]
