# Generated by Django 5.0.6 on 2024-07-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tortas', '0003_torta_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupcake',
            name='precio',
            field=models.DecimalField(decimal_places=3, default=5000, max_digits=10),
        ),
        migrations.AddField(
            model_name='modelado',
            name='precio',
            field=models.DecimalField(decimal_places=3, default=5000, max_digits=10),
        ),
        migrations.AddField(
            model_name='tortap',
            name='precio',
            field=models.DecimalField(decimal_places=3, default=5000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='torta',
            name='precio',
            field=models.DecimalField(decimal_places=3, default=5000, max_digits=10),
        ),
    ]
