# Generated by Django 5.0.6 on 2024-07-13 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tortas', '0006_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantity',
            new_name='cantidad',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cupcake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tortas.cupcake'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='modelado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tortas.modelado'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='torta_p',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tortas.tortap'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='torta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tortas.torta'),
        ),
    ]
