# Generated by Django 5.0.6 on 2024-07-13 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tortas', '0007_rename_quantity_cartitem_cantidad_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
