# Generated by Django 5.0.6 on 2024-07-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tortas', '0014_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='precio',
            field=models.PositiveIntegerField(default=5000),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='producto',
            field=models.CharField(max_length=100),
        ),
    ]
