# Generated by Django 5.0.6 on 2024-07-20 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tortas', '0017_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tortas.torta'),
        ),
    ]
