# Generated by Django 5.0.6 on 2024-07-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tortas', '0018_alter_cartitem_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='producto',
            field=models.CharField(max_length=100),
        ),
    ]
