# Generated by Django 5.0.6 on 2024-07-20 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tortas', '0020_alter_cartitem_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='producto',
            new_name='producto_type',
        ),
    ]
