# Generated by Django 5.0.6 on 2024-07-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tortas', '0021_rename_producto_cartitem_producto_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='producto_type',
            field=models.CharField(max_length=100),
        ),
    ]
